FROM anapsix/alpine-java
MAINTAINER Justin Lowry

RUN apk update
RUN apk add curl

RUN echo "PWD is: $PWD"
RUN echo "WORKDIR is: $WORKDIR"
RUN echo "PATH is: $PATH"

COPY soapapi/complete/request.xml /home/request.xml
COPY gs-producing-web-service-0.1.0.jar /home/gs-producing-web-service-0.1.0.jar

CMD ["java","-jar","/home/gs-producing-web-service-0.1.0.jar"]