FROM anapsix/alpine-java
MAINTAINER Justin Lowry

RUN apk update
RUN apk add curl

COPY ./request.xml /home/request.xml
COPY /var/jenkins_home/workspace/Pipeline-Jenkins/complete/target/gs-producing-web-service-0.1.0.jar /home/gs-producing-web-service-0.1.0.jar

CMD ["java","-jar","/home/gs-producing-web-service-0.1.0.jar"]